project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments
website:
  site-url: https://v-sekai.github.io
  repo-url: https://github.com/V-Sekai/V-Sekai.github.io.git
  repo-branch: master
  repo-actions: edit
  title: "V-Sekai Proposals"
  page-navigation: true
  opengraph: true
  navbar:
    left:
      - text: "Overview"
        file: CHANGELOG.md
    tools:
      - icon: twitter
        href: https://twitter.com/VSekaiOfficial
  sidebar:
    style: "docked"
    search: true
    contents:
      - decisions.qmd
      - roadmap_evergreen.qmd
      - CHANGELOG.md
  page-footer: 
    left: "2022, V-Sekai" 
    right: 
      - icon: github
        href: https://github.com/V-Sekai/V-Sekai

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
