project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments

website:
  site-url: https://v-sekai.github.io/manuals
  repo-url: https://github.com/V-Sekai/manuals
  repo-branch: master
  repo-actions: edit
  title: V-Sekai - Manuals
  page-navigation: true
  navbar:
    logo: 68604884.png
    logo-alt: V-Sekai
    background: primary
    search: true
    left:
      - text: "Changes"
        file: changelog.qmd
      - text: "Decisions"
        file: decisions.qmd
      - text: "Features"
        file: features.qmd
  page-footer:
    right:
      - icon: github
        href: https://github.com/V-Sekai/manuals

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly

filters:
  - quarto

freeze: true

editor: visual
