project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments

website:
  site-url: https://v-sekai.github.io
  repo-url: https://github.com/V-Sekai/V-Sekai.github.io
  repo-branch: master
  repo-actions: edit
  title: V-Sekai Developer Documentation
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Changelog"
        file: changelog.qmd
      - text: "Decisions"
        file: decisions.qmd
  sidebar:
    collapse-level: 1
    style: "docked"
    contents:
      - features/download_vsekai_groups_editor_4_x_from_our_cicd_system.md
      - documentation_guidelines.md
      - features/v-sekai.md
      - features/godot_engine_based.md
      - features/godot_vr.md
      - features/3d_creation_environment.md
      - features/distribute_custom_avatars_worlds.md
      - features/native_vrm_support.md
      - features/hosting_and_social_functions.md
      - features/spatialized_audio_and_voip.md
      - features/sandboxed_scripting_environment.md
      - features/customizable_server_rules.md
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/V-Sekai/V-Sekai
  search:
    algolia:
      index-name: prod_vsekai
      application-id: 2IE1M5GC5G
      search-only-api-key: 863078d76b639b43cee20498abb6b08a

format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: darkly

filters:
  - quarto

freeze: true

editor: visual
