project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments

website:
  site-url: https://v-sekai.github.io
  repo-url: https://github.com/V-Sekai/V-Sekai.github.io
  repo-branch: master
  repo-actions: edit
  title: V-Sekai
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Play"
        file: features/play_latest.md
      - text: "Avatars"
        file: features/design_avatars.md
      - text: "Places"
        file: features/design_worlds.md
      - text: "Games"
        file: features/build_games.md
      - text: "Move fast without breaking things"
        file: features/move_fast_without_breaking_things.md
      - text: "Changes"
        file: tables/changelog.qmd
      - text: "Decisions"
        file: tables/decisions.qmd
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/V-Sekai/V-Sekai

format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: darkly

filters:
  - quarto

freeze: true

editor: visual
