project:
  type: website
  output-dir: _site

resources:
  - docs/decisions/attachments

website:
  site-url: https://v-sekai.github.io
  repo-url: https://github.com/V-Sekai/V-Sekai.github.io
  repo-branch: master
  repo-actions: edit
  title: V-Sekai Developer Documentation
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Changelog"
        file: changelog.qmd
      - text: "Decisions"
        file: decisions.qmd
  sidebar:
    collapse-level: 1
    style: "docked"
    contents:
      - features/00_play_latest.md
      - features/01_help_guidelines.md
      - features/02_design_avatars.md
      - features/03_design_worlds.md
      - features/04_scripting_system.md
      - features/05_build_games.md
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/V-Sekai/V-Sekai
  search:
    algolia:
      index-name: prod_vsekai
      application-id: 2IE1M5GC5G
      search-only-api-key: 863078d76b639b43cee20498abb6b08a

format:
  html:
    toc: true
    theme: 
      light: flatly
      dark: darkly

filters:
  - quarto

freeze: true

editor: visual
