name: Publish Quarto
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Backup github issues to a markdown file.
      run: |
        pip3 install --user --upgrade setuptools
        pip3 install --user gh2md
        rm -rf _site
        rm -rf exported_issues
        rm -rf thirdparty/exported_issues
        rm -rf 00_thirdparty/exported_issues
        mkdir -p thirdparty/exported_issues
        $HOME/.local/bin/gh2md $GITHUB_REPOSITORY thirdparty/exported_issues --idempotent --multiple-files --no-prs
        git add thirdparty/exported_issues
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || git commit -am "Backup all issues into exported_issues."
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}
  quarto-linux:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3     
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true
      - name: Remove github issues
        run: |
          rm -rf thirdparty
      - run: |
          quarto render
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          TARGET_FOLDER: docs